config_version = 4
uuidupdated = true
# Please do not change the config version unless you know what you are doing!

# ---------------------------------------------------------------------------------------
# Protection Stones Config
# Block configs have been moved to the blocks folder.
# Does your config look messy? It's probably because of gradual config updates. Consider using the default configs.
# If you need the default configs again, you can get it from here: https://github.com/espidev/ProtectionStones/tree/master/src/main/resources
# ---------------------------------------------------------------------------------------


# Cooldown between placing protection blocks (in seconds). -1 to disable.
placing_cooldown = -1

# Base command for protection stones (change if conflicting with other commands)
base_command = "ps"

# Aliases for the command
aliases = [
    "pstone",
    "protectionstone",
    "protectionstones"
]